### ISSUE TITLE
2016 wisconsin full data set available here

### ISSUE THREAD

**Issue by happyjack27** [nvkelso/election-geodata#108]
wisconsin full data set available here:

http://data-ltsb.opendata.arcgis.com/datasets/0f074d32d43d486db5fd135e24424545_0

(2011-2016)

**Comment by nvkelso** [comment]
Verified this is 2011 geometries with official 2016 results added into the tables.

**Comment by happyjack27** [comment]
maybe i'm just rendering wrong, but there seems to be some funky (non-contiguous) precincts in wood county.

another source for wi 2011 shapefiles is available here: http://legis.wisconsin.gov/ltsb/gis/data/

which looks perfect to me.

i wrote software ( http://autoredistrict.org ) that i can use to:
* use the .shp files from that alternate source, but the dbf file from the original source
* pull in CVAP census data from census.gov.

and i could then upload that to my ftp site.  if you think that's worthwhile to give a shot.

**Comment by nvkelso** [comment]
@happyjack27 Can you verify if the 2014 data we already have is better?

- https://github.com/nvkelso/election-geodata/raw/master/data/55-wisconsin/statewide/2014/Wards_fall_2014.shape.zip

It's original source is the same as your latest comment (but for 2014):

- http://legis.wisconsin.gov/ltsb/gisdocs/ElectionData/GIS/Wards_fall_2014.shape.zip

I may hold off on merging my 2016 PR using your data for another couple weeks – I suspect 2016 geographies will be published by then by LEGIS.

**Comment by nvkelso** [comment]
In fact, looks like 2016 wards are here:

- http://data-ltsb.opendata.arcgis.com/datasets/6497103b939d41268a48905631f84de5_0

But I'm still going to hold off until they appear on the more official website (not just the ArcGIS open data portal).

**Comment by happyjack27** [comment]
i looked and they appear to have the exact same data (though of course one has more).
and i can't seem to find the shapefile errors i thought i saw in the ArcGIS one.   Shapes look exactly the same.

Maybe i'm drunk.

It looks perfectly fine.  i say go ahead and use it.

(also btw, if anything needs CVAP demographic data (or population for that matter), as long as it's in lat/long (as opposed to state plans), autoredistrict can automatically download block centroids and demographics, and use that to add the demographic data into the shapefile.  so consider that a solved problem.)

**Comment by nvkelso** [comment]
Cvap data sounds interesting!

**Comment by happyjack27** [comment]
1.    1990-2000 Election Data with 2011 Wards
http://data-ltsb.opendata.arcgis.com/datasets/6b9faecb50e448d689a5d266de5532cf_0
 
2.    2002-2010 Election Data with 2011 Wards
http://data-ltsb.opendata.arcgis.com/datasets/f0b8115085c649e3871a04d178a3e1b2_0
 
3.    2012-2020 Election Data with 2011 Wards
http://data-ltsb.opendata.arcgis.com/datasets/2718a4d6f65f4acdaea06b375cc0f583_0

**Comment by nvkelso** [comment]
There's new stuff now:

1. WI Municipal Wards (Fall 2016)
    http://data-ltsb.opendata.arcgis.com/datasets/6497103b939d41268a48905631f84de5_0?geometry=-92.402%2C43.626%2C-88.447%2C44.318
2. 1990-2000 WI Election Data with 2017 Wards
    http://data-ltsb.opendata.arcgis.com/datasets/1990-2000-wi-election-data-with-2017-wards

**Comment by nvkelso** [comment]
Closed via https://github.com/nvkelso/election-geodata/issues/109.
