### ISSUE TITLE
Virginia 2016 Off to the NW

### ISSUE THREAD

**Issue by sheadscott** [nvkelso/election-geodata#112]
I used ogr2orgr to convert Virginia 2016 to geojson: ogr2ogr -f GeoJSON -t_srs crs:84 [name].geojson [name].shp

The counties generated look okay except for they are moved slightly NW of the correct location. Most easily seen with Lee County here: https://github.com/sheadscott/county-voting-precincts/tree/master/va

I'm not very familiar with GIS so reached the limits of my troubleshooting. Is it an issue with the .prj file? I've converted other Shapefiles from this repo using the same techniques with no issues.

**Comment by happyjack27** [comment]
Personally I've found QGIS (free and open source) to be rather helpful in
processing such as converting formats and coordinate systems. It takes a
bit to learn the interface thou.  Hint: a lot of stuff is in right clicking
on a layer from the lower left layers tab - a layer is a file.

Also you can open up the .prj file in notepad to see the coordinate system
used.

**Comment by nvkelso** [comment]
Projections aren't any fun :( Looks like Virginia is in a special projection `EPSG:3857`:

https://github.com/nvkelso/election-geodata/blob/master/Makefile#L770-L773

The output from the Makefile in this repo does line up with expectations:

<img width="689" alt="screen shot 2017-08-04 at 23 19 52" src="https://user-images.githubusercontent.com/853051/28993465-bb0ab084-796b-11e7-9ebc-02c7d451e109.png">
