### ISSUE TITLE
nation.gpkg has dup Kentucky

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#117]
it's off in la-la-land, while main Kentucky is with the rest of the United States?! Doing QGIS zoom to layer only shows the la-la-land Kentucky.

<img width="918" alt="screen shot 2017-09-12 at 10 55 24" src="https://user-images.githubusercontent.com/853051/30340924-01d7cfb4-97a9-11e7-977e-fbfbef5dcf0d.png">

<img width="693" alt="screen shot 2017-09-12 at 10 55 05" src="https://user-images.githubusercontent.com/853051/30340894-e798df9e-97a8-11e7-8fce-249ed565d18a.png">

**Comment by migurski** [comment]
Could this be a feet-vs.-meters state plane problem?

**Comment by nvkelso** [comment]
Yes, that makes sense. It's a little odd since there are **2** KY in the
package – may need to force remove the package before adding it, or KY is
being added 2x.

**Comment by leehach** [comment]
Would like to point out that this also applies to the shapefile (which I downloaded earlier today).

**Comment by leehach** [comment]
Would like to point out that this also applies to the shapefile (which I downloaded earlier today).

**Comment by nvkelso** [comment]
Tracked this down to the source SHP having dup's – not due to our processing of the data. I'll push a PR with the fix.
