### ISSUE TITLE
Kansas 2016 precincts

### ISSUE THREAD

**Issue by karpet** [nvkelso/election-geodata#124]
The most populous counties in Kansas had some precinct shape change between 2012 (last state-wide map available) and 2016. I am locating 2016 geojson for these counties:

FIPS | County | Precincts
-- | -- | --
* [x] 20173 | Sedgwick County, KS | 447
* [x] 20091 | Johnson County, KS | 444
* [x] 20177 | Shawnee County, KS | 227
* [x] 20209 | Wyandotte County, KS | 111

All but Shawnee were available online. I have emailed Shawnee to ask if they have independent shapefile available for their map viewer http://gis.snco.us/ElectionViewer/

This is a follow-up to #9

**Comment by nvkelso** [comment]
Thanks, I appreciate your help!

I can look at update the Makefile for your PRs early next week – else have
a look for some of the other states that have mixed sources and copy the
pattern.

/cc @migurski to watch how the new Docker setup performs on the PRs :)

**Comment by karpet** [comment]
I have opened #125 to reflect the newer shapefiles.

**Comment by karpet** [comment]
No word yet from Shawnee - I'll bug them again tomorrow.

**Comment by karpet** [comment]
Shawnee is unresponsive. I have some hacks underway but have been interrupted by other work. Rather than block on that one county, how would you feel about merging #126 with what we have so far?

**Comment by karpet** [comment]
Shawnee in #131
