### ISSUE TITLE
Add 2016 election precinct shapes for California

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#13]
Priority 2 for population, not mentioned in original list.

**Comment by nvkelso** [comment]
- https://github.com/datadesk/california-2016-election-precinct-maps
- https://github.com/datadesk/california-2016-election-precinct-maps/tree/master/shapefiles

**Comment by nvkelso** [comment]
When researching & requesting data also ask for **matching election results** (_presidential, congressional, state house, and state senate_) in addition to the precinct shape data for 2016, **and for earlier election years** if available.

**Comment by nvkelso** [comment]
@migurski Can you add this one, please? (I think you've processed the LA Times data to be more useable.)

**Comment by migurski** [comment]
Will do!

**Comment by nvkelso** [comment]
- **2012** are gettable: https://github.com/aaron-strauss/precinct-shapefiles/tree/master/ca

Suggest no Makefile update for 2012 (it would just need to be redone for 2016 add).

**Comment by nvkelso** [comment]
I've got a local branch of this ready to go.
