### ISSUE TITLE
Add 2016 election precinct shapes for Texas

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#14]
Priority based on population

**Comment by nvkelso** [comment]
When researching & requesting data also ask for **matching election results** (_presidential, congressional, state house, and state senate_) in addition to the precinct shape data for 2016, **and for earlier election years** if available.

**Comment by dkastner** [comment]
TX precinct shapefiles as of 2010 redistricting are at ftp://ftpgis1.tlc.state.tx.us/2011_Redistricting_Data/Precincts/Geography/Precincts.zip  More here: http://www.tlc.state.tx.us/redist/districts/senate.html

Election results are managed by county clerks. For example, Harris County's results are in a difficult-to-parse PDF http://www.harrisvotes.com/ElectionResults.aspx

I have a script to parse Nov 2016 results that I can make available if interested.

**Comment by nvkelso** [comment]
@dkastner Adding script to parse the Nov 2016 results, and the output of same to this dir in the repo would be great, thank you!

Looks like OpenElections doesn't have much here:

- https://github.com/openelections/openelections-data-tx

**Comment by nvkelso** [comment]
- **2014** data:
    - https://github.com/aaron-strauss/precinct-shapefiles/tree/master/tx

**Comment by nvkelso** [comment]
Still looking for 2016 data...

**Comment by jmillermi** [comment]
2016 Precincts are here: ftp://ftpgis1.tlc.state.tx.us/2011_Redistricting_Data/Precincts/
2016 VTDs are here: ftp://ftpgis1.tlc.state.tx.us/2011_Redistricting_Data/VTDs/
Not sure why it's in a 2011 folder but if you open the readme it says they're from 2016.

I'm not sure exactly what the difference between precincts and VTDs is, but the VTDs can be matched to election results data from here: ftp://ftpgis1.tlc.state.tx.us/elections/

**Comment by migurski** [comment]
Thanks for hunting that down @jmillermi!

**Comment by dkastner** [comment]
Re: election districts vs VTDs:

(from the VTD README)

> VTDs can differ from actual election precincts because precincts do not always follow census geography.  The VTDs in the redistricting database closely correspond to the 8,832 precincts in effect for the 2016 general election. If a 2016 general election precinct does not match any census geography, it is consolidated with an adjacent precinct and given that precinct's corresponding VTD number.

As I understand it, if you want to get more accurate voting data for specific counties' precincts, go with the standard precinct data (aka electoral districts) coupled with official county clerk election results for each precinct.

If you want to correlate voting returns with census data, it's better to use the VTD shapefiles and return data since the VTD geographies may differ slightly from official county precincts.

**Comment by nvkelso** [comment]
@dkastner Thanks for the explanation, I'd been scratching my head over the difference!

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/election-geodata/commit/62390f66f468b5de43cebe426b717b7db36aaeca.
