### ISSUE TITLE
Add 2016 election precinct shapes for Washington

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#19]
Priority based on population

**Comment by nvkelso** [comment]
When researching & requesting data also ask for **matching election results** (_presidential, congressional, state house, and state senate_) in addition to the precinct shape data for 2016, **and for earlier election years** if available.

**Comment by almccon** [comment]
I have 2017 precinct shapefiles for Whatcom County and the City of Bellingham (inside Whatcom County, but a separate shapefile) here: http://documents.co.whatcom.wa.us/weblink8/browse.aspx?startid=2937976&&dbid=100

The two files have different columns in their attribute tables, so it will take a bit of transformation to combine them into one. For now I'm just converting each one to GeoJSON and uploading them separately. Pull request in #54.

**Comment by nvkelso** [comment]
- Voting Districts, Pierce County, Washington, 2010? - 427 features
    - http://geocommons.com/datasets?id=67504
    - https://raw.githubusercontent.com/geoiq/gc_data/master/datasets/67504.geojson

**Comment by nvkelso** [comment]
State just lists 2000 Census files:

- http://www.ofm.wa.gov/pop/geographic/tiger10/vtd10.zip

**Comment by almccon** [comment]
Checking on these: https://github.com/aaron-strauss/precinct-shapefiles/tree/master/wa

**Comment by almccon** [comment]
1. Downloaded statewide file from https://github.com/aaron-strauss/precinct-shapefiles/
2. Saved as GeoJSON (WGS 84 lat lon with 5 decimal place precision)
3. Also saved a TopoJSON version created using `topojson -q 1e5 -p -o statewide-prec-2016-nowater.topojson statewide-prec-2016-nowater.geojson`

See pull request #65.

**Comment by almccon** [comment]
Forgot to include a screenshot for reference (although @migurski's 
<img width="1098" alt="screen shot 2017-03-12 at 12 mar 7 07 51" src="https://cloud.githubusercontent.com/assets/1212178/23832502/a55427b6-06f2-11e7-80df-22f6ec82aea2.png">
