### ISSUE TITLE
Build process uses ubuntugis PPA for GDAL support

### ISSUE THREAD

**Issue by sigpwned** [nvkelso/election-geodata#193]
PR #162 changed the Dockerfile to use the ubuntugis PPA for GDAL support. This is likely to cause problems in the future as that PPA changes its package versions. We should change to [this bespoke PPA](https://launchpad.net/~election-geodata/+archive/ubuntu/ppa/) for this project, per conversation with @migurski @nvkelso [here](https://github.com/nvkelso/election-geodata/pull/162#issuecomment-426070717).

**Comment by migurski** [comment]
Andy, I’ve added you as an admin to [the EG PPA](https://launchpad.net/~election-geodata/+archive/ubuntu/ppa) so you can set it up exactly how it needs to be.
