### ISSUE TITLE
Full Ohio Precincts 2016 Shapefile

### ISSUE THREAD

**Issue by rogers19** [nvkelso/election-geodata#196]
This may be of interest: 
[https://github.com/mggg/ohio-precincts](https://github.com/mggg/ohio-precincts)

**Comment by nvkelso** [comment]
Wow! I’ve been struggling with per county and this looks like great alternative!

**Comment by rogers19** [comment]
It took a summer and 20+ contributors but it's something that can hopefully be useful :)

**Comment by migurski** [comment]
Amazing! I recognize a few names on that list of contributors, great work.

**Comment by nvkelso** [comment]
> The products of this project should be considered public and freely shareable. Please cite this repo and credit the Metric Geometry and Gerrymandering Group.

I checkout out the SHP version of the data and it looks good and the _license_ of the data is fine. Closing #7 in favor of this issue.

**Comment by nvkelso** [comment]
Closed via https://github.com/nvkelso/election-geodata/pull/198.
