### ISSUE TITLE
Add 2016 election precinct shapes for Wisconsin

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#2]
This state is in priority tier 1 (out of all US states) according to https://lawreview.uchicago.edu/sites/lawreview.uchicago.edu/files/uploads/82_2/04%20Stephanopoulos_McGhee_ART.pdf (via http://mike.teczno.com/notes/redistricting/measuring-efficiency-gap.html).

**Comment by nvkelso** [comment]
When researching & requesting data also ask for **matching election results** (_presidential, congressional, state house, and state senate_) in addition to the precinct shape data for 2016, **and for earlier election years** if available.

**Comment by nvkelso** [comment]
Guessing ward = precinct and good CSV coverage from Open Elections:

- https://github.com/openelections/openelections-data-wi

**Comment by nvkelso** [comment]
Similar to [Kansas issue](https://github.com/nvkelso/election-geodata/issues/9), US Census 2010 CSV is available listing each ward, but no geography:

- http://www2.census.gov/geo/docs/reference/codes/files/st55_wi_vtd.txt

**Comment by migurski** [comment]
Polling place locations with connected wards:

- http://elections.wi.gov/sites/default/files/page/polling_place_locations_2016_nov_general_xlsx_81288.xlsx

Some sample rows:

```
County	Muni	ReportingUnit	PollingPlaceName	PollingPlaceAddress	Phone	VotimgRoomArea	TypeOfBuilding	Longitude	Latitude	ElectionName
ADAMS COUNTY	CITY OF ADAMS	Ward 1-4	ADAMS CITY HALL	101 N MAIN ST, ADAMS, WI 53910-9805	6083396516		Government	-89.8176520318	43.9578974247	2016 General Election
ADAMS COUNTY	CITY OF WISCONSIN DELLS	Wards 5,9	WISCONSIN DELLS MUNICIPAL BUILDING	300 LA CROSSE ST, WISC DELLS, WI 53965-1568	608-254-2012		Government	-89.774916	43.624743	2016 General Election
ADAMS COUNTY	TOWN OF ADAMS	Wards 1-3	ADAMS TOWN HALL	1980 11TH AVE, FRIENDSHIP, WI 53934-9005	6083393980		Government	-89.7964935303	43.9695358276	2016 General Election
```

**Comment by migurski** [comment]
Result is not awful; certainly decent for drawing WI’s 8 districts over. I’d suggest that `accuracy = voronoi` might be part of our vocabulary?

![wi-voronoi](https://cloud.githubusercontent.com/assets/58730/23675091/02a62d20-032d-11e7-802f-2bf7f0bf5657.png)

**Comment by nvkelso** [comment]
Nice! I dig that terminology, similar to WOF. Combined with the township shapes this could be great start.

**Comment by migurski** [comment]
Many of these polling places map to multiple wards. I'm thinking we just let them overlap.

**Comment by nvkelso** [comment]
Initial overlap seems fine with me. We can pull them apart, later.

**Comment by nvkelso** [comment]
Wisconsin State Cartographer's Office, FTW:

- http://www.sco.wisc.edu/find-data/political-districts.html
- 2016 wards: http://data-ltsb.opendata.arcgis.com/datasets/6497103b939d41268a48905631f84de5_0.zip
- 2012 wards: http://data-ltsb.opendata.arcgis.com/datasets/0792c5d275e2466e93f551498b3d646c_0.zip

Which may have gotten them from here?

- https://mapservices.legis.wisconsin.gov/arcgis/rest/services/ArcGIS_Online

```
Senate Districts
Assembly Districts
Congressional Districts
Municipal Wards (LTSB stores wards as snapshots, e.g., Wards Spring 2015, Wards Fall 2015, etc.)
```

**Metadata for 2012**

These municipal wards were created by grouping Census 2010 population collection blocks into municipal wards. This project started with the release of Census 2010 geography and population totals to all 72 Wisconsin counties on March 21st, 2011. Census Geography and population totals to be used for local redistricting were made available on the Wisconsin Shape Editor for Local Redistricting (WISE-LR) website and the WISE-LR web application. The 180 day statutory timeline for local redistricting to occur in Wisconsin ended on September 19th, 2011. 

Wisconsin Legislative and congressional redistricting plans were enacted in the fall of 2011. 2011 Wisconsin Act 43 and Act 44 created new Assembly, Senate and Congressional lines for the state. These new districts were created using Census 2010 block geography. Some municipal wards that were created before Act 43 and 44 were enacted, which created municipal wards in some communities to be split between assembly, senate and congressional districts. 2011 Wisconsin Act 39 allowed communities to divide wards affected, along census blocks. Newly formed wards created under Wisconsin Act 39 would need named using alpha-numeric labels (ward 1 divided by an assembly district would become ward 1A and ward 1B, or the next sequential ward number would have to be used, ward 1 and ward 2). The process of dividing wards under Act 39 ended on April 10th, 2012. This link provides more information on Act 39. http://legis.wisconsin.gov/lrb/pubs/Lb/11Lb1.pdf

The United States Eastern District Federal Court on April 11th2012 ordered Assembly Districts 8 and 9 (both in the City of Milwaukee) be changed to follow the court’s description.

On September 19th, 2012 the Legislative Technology Services Bureau (LTSB) divided the few remaining municipal wards that were split by a 2011 Wisconsin Act 43 or 44 district line.

**Comment by nvkelso** [comment]
2012 State Assembly Districts:

- http://data-ltsb.opendata.arcgis.com/datasets/a907d137f96b49289d83172db8cf96f0_0.zip

2011 Wisconsin State Senate Districts:

- http://data-ltsb.opendata.arcgis.com/datasets/657bd028d3e2408fa2fac1af78b0760c_0.zip

2011 Wisconsin Congressional Districts:

- http://data-ltsb.opendata.arcgis.com/datasets/b52f3c49baa840adb070e7c56604de59_0.zip

**Comment by nvkelso** [comment]
@migurski better files for Wisconsin in this thread

**Comment by nvkelso** [comment]
Shapefiles of wards **with election results**:

- https://legis.wisconsin.gov/ltsb/gis/data/

```
GIS Shapefiles
2014 Fall Election Data (Zip)
2012 Fall Election Data (Zip)
Walker Recall Election Data (Zip)
2010 Election Data by Ward (Zip) current as of 4/17/2012
2008 Election Data by Ward (Zip)
2006 Election Data by Ward (Zip)
2004 Election Data by Ward (Zip)
2002 Election Data by Ward (Zip)
```

**Comment by nvkelso** [comment]
Turns out the shapefiles don't have the results, those are still a separate download from the same link mentioned in https://github.com/nvkelso/election-geodata/issues/2#issuecomment-284980892.

**Comment by migurski** [comment]
I’m doing some spot comparisons between the 2014 shapefile and OE’s 2014 precinct results for Wisconsin, and they appear to match. 🎉

**Comment by nvkelso** [comment]
Synergy, yo

**Comment by nvkelso** [comment]
This was closed in error before 2016 data was added, using https://github.com/nvkelso/election-geodata/issues/108 to track adding 2016 data.

**Comment by happyjack27** [comment]
i don't know if i should be proud or embarrased that my home state is "priority 1".

**Comment by nvkelso** [comment]
Luckily they have good Geo data ;)

**Comment by sheadscott** [comment]
Thank you for this project. I'm working on breaking down each county into a separate GeoJSON file. So far I have TX and I just finished WI. [https://github.com/sheadscott/county-voting-precincts/tree/master/wi](https://github.com/sheadscott/county-voting-precincts/tree/master/wi)

My goal is to have a map available for any Democratic Party website with precinct/ward chair info through this site: [https://demprecincts.org/](https://demprecincts.org/)

I have one up here for Travis County, TX. [http://www.traviscountydemocrats.org/people/county-precinct-chairs/](http://www.traviscountydemocrats.org/people/county-precinct-chairs/)

BTW - Austin is the largest city in the country without an anchor congressional district. We have 6 representatives and 5 are Republican 👎
