### ISSUE TITLE
Request to use data on tetra.earth

### ISSUE THREAD

**Issue by dougbutner** [nvkelso/election-geodata#205]
Hey Nathaniel, really great to discover your work. 

Requesting permission to use your work. 

## Context 
We want to show the US how easy politics can be using blockchain, so we're working on an election map for 2024 to generate buzz around blockchain voting. 

We're building community tools to bring people together with their fellow citizens,

It's not politics, just geotemporal systems, and seeing this as an opportunity to engage people. 

The map will help us a lot.

**Comment by nvkelso** [comment]
The data is free to use by anyone, see https://github.com/nvkelso/election-geodata#credits.

That said, it's a little old now so if you're looking for vintage data great. If you need new boundaries you'll need to look at the sources and pull new versions.
