### ISSUE TITLE
Add 2016 election precinct shapes for Maryland

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#23]
Priority based on population

**Comment by nvkelso** [comment]
When researching & requesting data also ask for **matching election results** (_presidential, congressional, state house, and state senate_) in addition to the precinct shape data for 2016, **and for earlier election years** if available.

**Comment by nvkelso** [comment]
- Voting Districts, Maryland, 2000 – NOT STATEWIDE
    - http://geocommons.com/datasets?id=5124
    - http://www.census.gov/geo/www/cob/vt2000.html
    - https://raw.githubusercontent.com/geoiq/gc_data/master/datasets/5124.geojson

**Comment by eczajk1** [comment]
2010 precincts shapefile: http://planning.maryland.gov/PDF/Redistricting/2010zip/precinct2010.zip

... via http://planning.maryland.gov/redistricting/2010/precinct.shtml

**Comment by nvkelso** [comment]
For historical, I think I found complete set of Maryland 2000 / 2004 precincts on a hard drive...

**Comment by nvkelso** [comment]
I'm dubious this **2012** data is not Census, but let's look:

- https://github.com/aaron-strauss/precinct-shapefiles/tree/master/md

**Comment by nvkelso** [comment]
The 2012 data link from Aaron Strauss is to a 404ing GeoCommons assets (the JSON is just the metadata in his repo).

**Comment by eczajk1** [comment]
My understanding is that the 2010 precincts are based off of the 2010 census, and so the 2010 precincts data that we have is relevant for subsequent elections.  Is there a way to indicate this in the repo?

**Comment by nvkelso** [comment]
Yes, I'll update the readme and mark them 2016.

**Comment by nvkelso** [comment]
Updated in 583d6f2f1eb80c07954450d838d75004d0188742.

![render](https://cloud.githubusercontent.com/assets/853051/24581800/38051310-16d7-11e7-91b2-9c64241fdcfc.png)

**Comment by nvkelso** [comment]
Closed #23 via #106.
