### ISSUE TITLE
Add 2016 election precinct shapes for Virginia

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#4]
This state is in priority tier 1 (out of all US states) according to https://lawreview.uchicago.edu/sites/lawreview.uchicago.edu/files/uploads/82_2/04%20Stephanopoulos_McGhee_ART.pdf (via http://mike.teczno.com/notes/redistricting/measuring-efficiency-gap.html).

**Comment by nvkelso** [comment]
When researching & requesting data also ask for **matching election results** (_presidential, congressional, state house, and state senate_) in addition to the precinct shape data for 2016, **and for earlier election years** if available.

**Comment by nvkelso** [comment]
- Many years
    - https://github.com/openelections/openelections-results-va/tree/master/raw

**Comment by nvkelso** [comment]
- Voting Districts, Virginia, 2000 MAJOR CITIES ONLY
    - http://geocommons.com/datasets?id=5156
    - http://www.census.gov/geo/www/cob/vt2000.html
    - https://raw.githubusercontent.com/geoiq/gc_data/master/datasets/5156.geojson

**Comment by nvkelso** [comment]
Results: 

- https://apps.elections.virginia.gov/SBE_CSV/ELECTIONS/ELECTIONRESULTS/2016/

**Comment by grahamimac** [comment]
June 2016 from VA public access project is a good start https://github.com/vapublicaccessproject/va-precinct-maps-2016
