### ISSUE TITLE
Add 2016 election precinct shapes for Vermont

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#48]
Priority 4 based on population

**Comment by nvkelso** [comment]
When researching & requesting data also ask for **matching election results** (_presidential, congressional, state house, and state senate_) in addition to the precinct shape data for 2016, **and for earlier election years** if available.

**Comment by wboykinm** [comment]
Dibs.

**Comment by wboykinm** [comment]
@nvkelso Give a merge if cool: https://github.com/nvkelso/election-geodata/pull/59

**Comment by nvkelso** [comment]
@wboykinm Thank you! Can you also look around for the voter tabulation areas / precincts, please?

**Comment by nvkelso** [comment]
- Voting Districts, Vermont, 2000
    - http://geocommons.com/datasets?id=5155
    - http://www.census.gov/geo/www/cob/vt2000.html
    - https://raw.githubusercontent.com/geoiq/gc_data/master/datasets/5155.geojson

**Comment by wboykinm** [comment]
Ah, okay. I was unclear on how Vermont's definition of "precinct" fits into the national scheme. The "voter tabulation areas" in Vermont consist of small boundaries that mostly correspond with town boundaries in rural areas and wards in cities. Nobody votes [at the county seat](http://geocommons.com/datasets?id=515), for any election, local, state or federal, so I don't know where the above examples are coming from. The [polling places](https://www.sec.state.vt.us/media/822350/2017-vt-primary-general-polling-places.xls5) reflect this. 

I'll see if the "voter tabulation area" boundaries actually exist; even the secretary of state's office considers these to be point locations, so we might need to do some data generation.

**Comment by nvkelso** [comment]
Super interesting, thanks for the background! Sounds similar to Kansas and Wisconsin setup. Census CoSub may help here, plus city wards.

**Comment by wboykinm** [comment]
@nvkelso I spoke with the SoS's office and they confirmed that no boundary layer exists that matches their level of results reporting. I'm going to build one for now, but VCGI has also offered to make and host an authoritative one for some unspecified point in the future.

With that in mind, is there any plan here for an openaddresses-style manifest system for importing and speccing from a remote, authoritative source?

**Comment by wboykinm** [comment]
@nvkelso Another silly q: do we have an accepted way of including results (2016 and historical) in here? Prefer 

- csv with primary key, or 
- as properties on the geoms?

**Comment by nvkelso** [comment]
Good question!

I'm fine including results (2016 and historical) in this repo for ease of
use. Eventually they should move to the Open Elections repo, but even the
geometries in this repo should probably move to something else, like Who's
On First ;)

I prefer CSV with primary key. They should probably go into a new top-level
`results` dir (next to data).

**Comment by wboykinm** [comment]
That's great - I like that as well. Thanks!

**Comment by nvkelso** [comment]
Data is in, I'll need to update the Makefile.

**Comment by nvkelso** [comment]
(Fat fingers)

**Comment by nvkelso** [comment]
Makefile was updated a few PRs ago, closing.
