### ISSUE TITLE
Add 2016 election precinct shapes for Florida

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#5]
This state is in priority tier 1 (out of all US states) according to https://lawreview.uchicago.edu/sites/lawreview.uchicago.edu/files/uploads/82_2/04%20Stephanopoulos_McGhee_ART.pdf (via http://mike.teczno.com/notes/redistricting/measuring-efficiency-gap.html).

**Comment by nvkelso** [comment]
When researching & requesting data also ask for **matching election results** (_presidential, congressional, state house, and state senate_) in addition to the precinct shape data for 2016, **and for earlier election years** if available.

**Comment by nvkelso** [comment]
- https://github.com/openelections/openelections-results-fl/blob/master/raw/20161108__fl__general__precinct__raw.csv
- https://github.com/openelections/openelections-results-fl/blob/master/raw/20141104__fl__general__precinct__raw.csv
- https://github.com/openelections/openelections-results-fl/blob/master/raw/20121106__fl__general__precinct__raw.csv

**Comment by nvkelso** [comment]
Looks like the source of those is:

- http://dos.myflorida.com/elections/data-statistics/elections-data/precinct-level-election-results/

**Comment by nvkelso** [comment]
Emailed DivElections@dos.myflorida.com asking about GIS shape sources...

**Comment by nvkelso** [comment]
US Census 2010 `vtd` data here is more on the numbered precincts per county basis than something useful to geocode to (like was the case in Kansas).

- http://www2.census.gov/geo/docs/reference/codes/files/st12_fl_vtd.txt

**Comment by nvkelso** [comment]
- Voting Districts, Pinellas County, Florida, 2010 - 400 count
    - http://geocommons.com/datasets?id=72803
    - https://raw.githubusercontent.com/geoiq/gc_data/master/datasets/72803.geojson

**Comment by nvkelso** [comment]
Related:

- https://github.com/aaron-strauss/precinct-shapefiles/tree/master/fl

**Comment by nvkelso** [comment]
The Florida Secretary of State office wrote back and seemed to say they would send me a DVD of "filez", but inconclusive.

**Comment by mxndrwgrdnr** [comment]
@nvkelso Have you seen [Harvard's Election Data Archive](http://projects.iq.harvard.edu/eda/home)? Seems pretty extensive although it looks like most of the precinct shapes haven't been updated since the 2010 cycle, so I don't know how much better this is than what's available from the Census. Here are the notes from the Florida data: 

>Summary: 
>
> 2008 precinct level voting data has been merged with 2010 voting data provided by the Florida Secretary of State's office. There was limited re-precincting between 2008 and 2010. 
>
> There are vote returns for all 6,984 precincts in 2010, and 6,803 out of 6,984 observations in the 2010 SOS file have been matched with a 2008 vote total. The majority of unmatched precincts are located in Miami-Dade and Osceola county. The precincts in the SOS data set are different from Census VTDs; therefore, we do not have voting age population for each unit.

![screen shot 2017-03-20 at 4 16 06 pm](https://cloud.githubusercontent.com/assets/1395651/24125962/91c4b9a8-0d88-11e7-9353-1f0618349bc5.png)

**Comment by nvkelso** [comment]
@mxndrwgrdnr Thanks for the tip! I think I have the same 2010 US Census precincts that Harvard used already?

The **Florida Secretary of State** responded to my FOIA request and sent me a DVD that they say has 2016 precincts. I'll know more tomorrow once I dust off the DVD reader :)

**Comment by mxndrwgrdnr** [comment]
No problem!

**Comment by nvkelso** [comment]
Got the DVD loaded locally, ready for PR :)

**Comment by nvkelso** [comment]
Here's the mixed 2012 and 2015/2016 data that the SoS has assembled, by county. 

**NOTES:** 

1. A couple counties didn't dissolve their _something_ into precincts, but the something has precinct numbers.
2. There are a couple more I could add if I could convert a different GIS format into standard SHP.
3. Some other counties only list out which census blocks are in what precinct. Yet some others just have precinct names and voting place addresses.

<img width="508" alt="screen shot 2017-03-21 at 11 16 08 pm" src="https://cloud.githubusercontent.com/assets/853051/24184741/b34e6ee8-0e8c-11e7-8697-801500511084.png">
