### ISSUE TITLE
Add 2016 election precinct shapes for Oregon

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#51]
Priority 3 based on population

**Comment by nvkelso** [comment]
When researching & requesting data also ask for **matching election results** (_presidential, congressional, state house, and state senate_) in addition to the precinct shape data for 2016, **and for earlier election years** if available.

**Comment by nvkelso** [comment]
Many counties, but many files and not clear if there are precincts:

- https://github.com/openelections/openelections-sources-or

**Comment by nvkelso** [comment]
- Voting Districts, around Bend, Oregon, 2014? - 52 count
    - http://geocommons.com/datasets?id=104744
    - https://raw.githubusercontent.com/geoiq/gc_data/master/datasets/104744.geojson

**Comment by joehand** [comment]
Portland metro area precincts are available from Metro [as a shapefile](http://rlisdiscovery.oregonmetro.gov/?action=viewDetail&layerID=276) (doesn't say what year). 

* Unofficial Oregon 2016 county level results available as table at http://results.oregonvotes.gov/ (seems like precinct should be available there but I couldn't find it).

**Comment by nvkelso** [comment]
Matt Hampton at Metro probably knows who knows. You have his contact?

**Comment by nvkelso** [comment]
I've [asked](https://twitter.com/kelsosCorner/status/841004117891866625) one of the authors of this interactive map for data (2014) via Twitter: 

- http://gov.oregonlive.com/election/2014/general/precincts/

**Comment by nvkelso** [comment]
I've asked Matt via email.

**Comment by nvkelso** [comment]
Sounds like we can get (most populated counties) of the 2014 data from the Oregon Live source :)

Everyone is pointing to the Metro precinct shapes as the best source, there may also be a similar southern Oregon consortium called GeoMoose of all things. Something like? 

- http://www.geomoose.org/wiki/index.php/Oregon_County_Consortium

**Comment by nk9** [comment]
@nvkelso said this earlier:

> When researching & requesting data also ask for matching election results

I've been working to get election _results_ from counties, but not shapefiles. I would say that requesting this data is unnecessary at this point. I have requests in for all counties with [missing results](https://github.com/openelections/openelections-data-or/blob/master/county_matrix.csv). See the [issues](https://github.com/openelections/openelections-data-or/issues) of the various counties where I've been tracking most communication with the various county clerks. Current status of the Oregon OE election results is as follows:

```By election:
       Complete   438  67.6%
 Source missing    81  12.5%
     Incomplete   129  19.9%
          Total   648

By precinct:
       Complete 18088  74.1%
 Source missing  1613   6.6%
     Incomplete  4707  19.3%
          Total 24408```

**Comment by nvkelso** [comment]
@nk9 Awesome, thanks for the update, great work! We'll stay focused on the shapefiles in this `election-geodata` repo :)

**Comment by nvkelso** [comment]
The Portland Metro has [metadata](http://rlisdiscovery.oregonmetro.gov/metadataviewer/display.cfm?meta_layer_id=276), including the following lineage:

- Process Description	
    - The precincts file was updated with data from the three counties. If any further updates are available before the November election, they will be posted on the DRC ftp site.
    - Process date: 2000-07
- Process Description	
    - Projection information (.prj file), compatible with ArcGIS 8.1, was added to the layer.
    - Process date: 2001-07-15
- Process Description	
    - Incorporated 2006 precincts from Multnomah County.
    - Process date: 2006-08-11
- Process Description	
    - Updated boundaries based on data provided by our data partners. Data now maintained as a geodatabase in SDE.
    - Process date: 2008-11-03
- Process Description	
    - Voter Precincts following the boundary between the states of Oregon and Washington were updated to precise state boundary line coordinates. The boundary between Oregon and Washington is defined by ORS 186.520 which lists latitude and longitude coordinate stations connected by a series of straight lines along length of the boundary.
    - Process date: 2012-04-23
- Process Description	
    - Major edits to Washington County and minor edits to Clackamas County, reflective of precincts for upcoming November election.
- Process date: 2016-11-02

**Comment by nvkelso** [comment]
I've added 2016 precinct shapes via https://github.com/nvkelso/election-geodata/pull/86, but we should go back thru and ask Metro for the earlier files so we have a complete set (metadata says the shapes changed quite a bit version to version).

**Comment by nk9** [comment]
Does the focus on getting the shape files from Multnomah/Portland mean that you've hit a dead end with getting them in bulk from the Oregon SoS?

**Comment by nvkelso** [comment]
Someone needs to call / email SOS, yes.

**Comment by nk9** [comment]
OK, I'm already in touch with Nick Kramer at OR SoS for the outstanding results, so I'll ask about the shapefiles as well.

**Comment by nvkelso** [comment]
Thanks!

**Comment by nvkelso** [comment]
From Kevin Rancik (required credit CC-BY):

- 2016 data for almost all Oregon counties (use GeoDB): http://www.kevinrancik.com/home/research/election-2016
- 2012 data for a few less Oregon counties (SHP): http://www.kevinrancik.com/home/research/election-2012

Found via attribution note on https://decisiondeskhq.com/data-dives/creating-a-national-precinct-map/.

**Comment by nvkelso** [comment]
The missing 2016 county precinct shapes are:

_County name, FIPS code, population_

- [ ] Baker `001` pop 16,510
- [ ] Lake `037` pop 8,015
- [ ] Lincoln `041` pop 47,735
- [ ] Tillamook `057` pop 25,920
- [ ] Union `061` pop 26,745
- [ ] Wallowa `063` pop 7,140
- [ ] Wheeler `069` pop 1,465

**Comment by nvkelso** [comment]
@nk9 Some good Oregon precinct data found above :)

**Comment by nvkelso** [comment]
The 2016 GeoDB mentioned in https://github.com/nvkelso/election-geodata/issues/51#issuecomment-290966525 isn't openable on my Mac using QGIS or on a desktop Windows machine in ArcExplorer or ArcGIS.

**Comment by nk9** [comment]
I've followed up with Nick Kramer, since it's been several weeks since I asked about the shape files. Will let you know when I hear back from him.

**Comment by nvkelso** [comment]
Do you have access to newer ArcGIS to see if you can convert the 2016 GeoDB to SHP?

**Comment by bahoo** [comment]
I am no GIS expert, but `Layer -> Add Layer -> Add Vector Layer` did the trick for me, FWIW. QGIS v2.18.2, macOS Sierra 10.12.4.

I converted them to shapefiles, also:
- https://s3-us-west-2.amazonaws.com/jonculver.com/gis/ORWA_2016+ORWA_PresidentByPrecinct.zip
- https://s3-us-west-2.amazonaws.com/jonculver.com/gis/ORWA_2016+ORWA_SenateByPrecinct.zip
- https://s3-us-west-2.amazonaws.com/jonculver.com/gis/ORWA_2016+OR_M97byPrecinct.zip

**Comment by nvkelso** [comment]
Wow! You've given me reason to upgrade my very old QGIS install :) Ready to rock and roll.

<img width="939" alt="screen shot 2017-04-03 at 09 09 43" src="https://cloud.githubusercontent.com/assets/853051/24618964/82110dde-184d-11e7-8b7b-ed2b7058a289.png">

**Comment by nvkelso** [comment]
Now it's just the 1/2 dozen missing counties of precincts in Montana and the'll be "shapes for everyone" :)

**Comment by nvkelso** [comment]
Verified new GDAL/OGR 2.1 and QGIS 2.18 on Mac will open the GeoDB fine!

**Comment by nvkelso** [comment]
A few more counties in Oregon will need research: https://github.com/nvkelso/election-geodata/issues/110.
