### ISSUE TITLE
Add 2016 election precinct shapes for Pennsylvania

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#52]
Priority 2 based on population

**Comment by jinlong25** [comment]
PA 2011 Voting District Boundary Shapefiles: http://www.redistricting.state.pa.us/Data.cfm
<img width="879" alt="vtds" src="https://cloud.githubusercontent.com/assets/4049548/23826129/a239ca20-064a-11e7-8252-82b0b13fc852.png">

**Comment by nvkelso** [comment]
Perhaps individual counties have newer data (eg: https://www.arcgis.com/home/webmap/viewer.html?webmap=8a294600593846a6b4e2320ead4775eb), but not seeing any state-wide so closing this one.
