### ISSUE TITLE
Add 2016 election precinct shapes for Ohio

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/election-geodata#7]
This state is in priority tier 1 (out of all US states) according to https://lawreview.uchicago.edu/sites/lawreview.uchicago.edu/files/uploads/82_2/04%20Stephanopoulos_McGhee_ART.pdf (via http://mike.teczno.com/notes/redistricting/measuring-efficiency-gap.html).

Since the state of Ohio doesn't keep centralized records, we need to rely on older Census 2010 data supplemented with [county gov't sources](https://github.com/nvkelso/election-geodata/issues/7#issuecomment-288617963). 

Here's the top 20 counties by population – lookup the county contact which usually has a website a poke around their sites:

- [ ] **Cuyahoga County** - `035` Cleveland pop: `1280122`
- [ ] **Franklin County** -`049` Columbus pop: `1163414`
- [ ] **Hamilton County** - `061` Cincinnati pop: `802374`
- [ ] **Summit County** - `153` Akron     pop: `541781`
- [ ] **Montgomery Co** - `113` Dayton     pop: `535153`
- [ ] **Lucas County** - `095` Toledo     pop: `441815`
- [ ] **Stark County** - `151` Canton     pop: `375586`
- [ ] **Butler County** - `017` Hamilton pop: `368130`
- [ ] **Lorain County** - `093` Elyria     pop: `301356`
- [ ] **Mahoning County** - `099` Youngstown pop: `238823`
- [ ] **Lake County** - `085`   Painesville pop: `230041`
- [ ] **Warren County** - `165` Lebanon     pop: `212693`
- [ ] **Trumbull County** - `155` Warren     pop: `210312`
- [ ] **Clermont County** - `025` Batavia     pop: `197363`
- [ ] **Medina County** - `103` Medina     pop: `176395`
- [ ] **Delaware County** - `041` Delaware pop: `174214`
- [ ] **Licking County** - `089` Newark pop: `166492`
- [ ] **Greene County** - `057` Xenia     pop: `161573`
- [ ] **Portage County** - `133` Ravenna     pop: `161419`
- [ ] **Fairfield Co** - `045` Lancaster pop: `146156`

**Comment by nvkelso** [comment]
When researching & requesting data also ask for **matching election results** (_presidential, congressional, state house, and state senate_) in addition to the precinct shape data for 2016, **and for earlier election years** if available.

**Comment by nvkelso** [comment]
Our friends over at Open Elections have 2016 and 2014 precinct results (for some races?):

- https://github.com/openelections/openelections-data-oh/blob/master/2016/20160315__oh__primary__precinct.csv
- https://github.com/openelections/openelections-data-oh/blob/master/2014/20141104__oh__general__precinct.csv

**Comment by nvkelso** [comment]
- Voting Districts, Geauga County, Ohio, 1996 - 93 count
    - http://geocommons.com/datasets?id=112124
    - https://raw.githubusercontent.com/geoiq/gc_data/master/datasets/112124.geojson

**Comment by nvkelso** [comment]
Maybe somewhere in here? 

- https://www.sos.state.oh.us/elections/candidates/district%20maps.aspx

**Comment by nvkelso** [comment]
Erie county precincts:

- http://downloads.ddti.net/ErieOH/Erie_County_Voting_Precincts.zip
- **source:** http://downloads.ddti.net/ErieOH/

**Comment by nvkelso** [comment]
Mahoning county precincts:

- http://gisapp.mahoningcountyoh.gov/Public_FTP_Folder/Shape_Files/
- http://gisapp.mahoningcountyoh.gov/Public_FTP_Folder/Shape_Files/Precincts_2012.zip
- http://gisapp.mahoningcountyoh.gov/Public_FTP_Folder/Shape_Files/Precincts_2015.zip
- http://gisapp.mahoningcountyoh.gov/Public_FTP_Folder/Shape_Files/Voting_Precincts.zip
- http://gisapp.mahoningcountyoh.gov/Public_FTP_Folder/Shape_Files/Voting_Locations.zip

**Comment by nvkelso** [comment]
Statewide, note sure of source. Inside cities it's good polygons, outside it's funky clustr like shapes.

- https://github.com/aaron-strauss/precinct-shapefiles/tree/master/oh

<img width="835" alt="screen shot 2017-03-08 at 00 53 45" src="https://cloud.githubusercontent.com/assets/853051/23696721/c7a7ac36-0399-11e7-8eea-b650b429bc48.png">

**Comment by nvkelso** [comment]
Sent an "email" to Ohio SoS using their web form asking for 2016 precinct shapes (and earlier):

- https://www.sos.state.oh.us/SOS/elections/ContactUsElections.aspx

**Comment by nvkelso** [comment]
Heard back from SoS, will need to contact individual counties:

```
Dear Mr. Kelso,
 
Thank you for contacting the office of Ohio Secretary of State Jon Husted.
 
In Ohio, each county board of elections is responsible for setting precinct
boundaries; therefore, for assistance with the information that you are looking
for, you would need to contact the county boards of elections.  A directory for
all county boards can be found here: 

http://www.sos.state.oh.us/SOS/elections/electionsofficials/boeDirectory.aspx#dir.
 
I hope you find this information helpful.  Please contact me if I may be of further
assistance.
 
Sincerely,
 
Emily Groseclose
Legislative Liaison
P: (614) 466-7691
```

**Comment by nvkelso** [comment]
Here's the full list of counties, I'll add checkmarks at the top of this issue for the ones I think we should contact for best available data (the rest can use 2010 US Census data, probably hasn't changed much):

County | FIPS County Code | County Seat | Population
------ | ---------------- | ----------- | ----------
Adams County | 001 | West Union | 28550
Allen County | 003 | Lima | 106331
Ashland County | 005 | Ashland | 53139
Ashtabula County | 007 | Jefferson | 101497
Athens County | 009 | Athens | 64757
Auglaize County | 011 | Wapakoneta | 45949
Belmont County | 013 | St. Clairsville | 70400
Brown County | 015 | Georgetown | 44846
Butler County | 017 | Hamilton | 368130
Carroll County | 019 | Carrollton | 28836
Champaign County | 021 | Urbana | 40097
Clark County | 023 | Springfield | 138333
Clermont County | 025 | Batavia | 197363
Clinton County | 027 | Wilmington | 42040
Columbiana County | 029 | Lisbon | 107841
Coshocton County | 031 | Coshocton | 36901
Crawford County | 033 | Bucyrus | 43784
Cuyahoga County | 035 | Cleveland | 1280122
Darke County | 037 | Greenville | 52959
Defiance County | 039 | Defiance | 39037
Delaware County | 041 | Delaware | 174214
Erie County | 043 | Sandusky | 77079
Fairfield County | 045 | Lancaster | 146156
Fayette County | 047 | Washington Court House | 29030
Franklin County | 049 | Columbus | 1163414
Fulton County | 051 | Wauseon | 42698
Gallia County | 053 | Gallipolis | 30934
Geauga County | 055 | Chardon | 93389
Greene County | 057 | Xenia | 161573
Guernsey County | 059 | Cambridge | 40087
Hamilton County | 061 | Cincinnati | 802374
Hancock County | 063 | Findlay | 74782
Hardin County | 065 | Kenton | 32058
Harrison County | 067 | Cadiz | 15864
Henry County | 069 | Napoleon | 28215
Highland County | 071 | Hillsboro | 43589
Hocking County | 073 | Logan | 29380
Holmes County | 075 | Millersburg | 42366
Huron County | 077 | Norwalk | 59626
Jackson County | 079 | Jackson | 33225
Jefferson County | 081 | Steubenville | 69709
Knox County | 083 | Mount Vernon | 60921
Lake County | 085 | Painesville | 230041
Lawrence County | 087 | Ironton | 62450
Licking County | 089 | Newark | 166492
Logan County | 091 | Bellefontaine | 45858
Lorain County | 093 | Elyria | 301356
Lucas County | 095 | Toledo | 441815
Madison County | 097 | London | 43435
Mahoning County | 099 | Youngstown | 238823
Marion County | 101 | Marion | 66501
Medina County | 103 | Medina | 176395
Meigs County | 105 | Pomeroy | 23770
Mercer County | 107 | Celina | 40814
Miami County | 109 | Troy | 102506
Monroe County | 111 | Woodsfield | 14642
Montgomery County | 113 | Dayton | 535153
Morgan County | 115 | McConnelsville | 15054
Morrow County | 117 | Mount Gilead | 34827
Muskingum County | 119 | Zanesville | 86074
Noble County | 121 | Caldwell | 14645
Ottawa County | 123 | Port Clinton | 41428
Paulding County | 125 | Paulding | 19614
Perry County | 127 | New Lexington | 36058
Pickaway County | 129 | Circleville | 55698
Pike County | 131 | Waverly | 28709
Portage County | 133 | Ravenna | 161419
Preble County | 135 | Eaton | 42270
Putnam County | 137 | Ottawa | 34499
Richland County | 139 | Mansfield | 124475
Ross County | 141 | Chillicothe | 78064
Sandusky County | 143 | Fremont | 60944
Scioto County | 145 | Portsmouth | 79499
Seneca County | 147 | Tiffin | 56745
Shelby County | 149 | Sidney | 49423
Stark County | 151 | Canton | 375586
Summit County | 153 | Akron | 541781
Trumbull County | 155 | Warren | 210312
Tuscarawas County | 157 | New Philadelphia | 92582
Union County | 159 | Marysville | 52300
Van Wert County | 161 | Van Wert | 28744
Vinton County | 163 | McArthur | 13435
Warren County | 165 | Lebanon | 212693
Washington County | 167 | Marietta | 61778
Wayne County | 169 | Wooster | 114520
Williams County | 171 | Bryan | 37642
Wood County | 173 | Bowling Green | 125488
Wyandot County | 175 | Upper Sandusky | 22615

**Comment by mxndrwgrdnr** [comment]
Just got the 2016 shapes for the following counties:

- Allen
- Ashtabula
- Athens
- Auglaze
- Belmont
- Brown
- Butler
- Champaign
- Portage
- Tuscarawas

![ohio_precincts](https://cloud.githubusercontent.com/assets/1395651/25245952/005d4f34-25bb-11e7-9977-35ce6fb1cf03.png)

How would you like me to upload them?

**Comment by nvkelso** [comment]
You rock!

You can either submit them as a ZIP'd shapefile into this repo, or post
anywhere on the internet that's public (even a temp FTP) and I can grab
them and ingest :)

Can you tell me more about where you got the data from? I generally note
the source information (with URLs or contact info) in the README for each
state.

**Comment by mxndrwgrdnr** [comment]
Great! I'll attach them here.

I have a friend in Ohio (my home state) who has done work for the state in the past. According to him these have all come from county BOE's so far, so the data have varying levels of detail -- some have voting locations, or the URL's of the map data, etc. All should have the precinct ID, at a minimum. I'll follow up with him to try to get better attribution information, but maybe we could use his e-mail as a contact for now? Anyway, he's put in a "statewide request" (not sure how that works exactly) for precinct maps and they are starting to trickle in. Hopefully we'll have more in the next couple weeks/months. I'll be sure to keep uploading them here as he sends them my way. 
 
[OHIO_PRCT_1.zip](https://github.com/nvkelso/election-geodata/files/945227/OHIO_PRCT_1.zip)

**Comment by wboykinm** [comment]
## [A hack of a] Progress Tracker

- [ ] Adams County
- [ ] Allen County
- [ ] Ashland County
- [ ] Ashtabula County
- [ ] Athens County
- [ ] Auglaize County
- [ ] Belmont County
- [ ] Brown County
- [ ] Butler County
- [ ] Carroll County
- [ ] Champaign County
- [ ] Clark County
- [ ] Clermont County
- [ ] Clinton County
- [ ] Columbiana County
- [ ] Coshocton County
- [ ] Crawford County
- [ ] Cuyahoga County
- [ ] Darke County
- [ ] Defiance County
- [ ] Delaware County
- [ ] Erie County
- [ ] Fairfield County
- [ ] Fayette County
- [ ] Franklin County
- [ ] Fulton County
- [ ] Gallia County
- [ ] Geauga County
- [ ] Greene County
- [ ] Guernsey County
- [ ] Hamilton County
- [ ] Hancock County
- [ ] Hardin County
- [ ] Harrison County
- [ ] Henry County
- [ ] Highland County
- [ ] Hocking County
- [ ] Holmes County
- [ ] Huron County
- [ ] Jackson County
- [ ] Jefferson County
- [ ] Knox County
- [ ] Lake County
- [ ] Lawrence County
- [ ] Licking County
- [ ] Logan County
- [ ] Lorain County
- [ ] Lucas County
- [ ] Madison County
- [ ] Mahoning County
- [ ] Marion County
- [ ] Medina County
- [ ] Meigs County
- [ ] Mercer County
- [ ] Miami County
- [ ] Monroe County
- [ ] Montgomery County
- [ ] Morgan County
- [ ] Morrow County
- [ ] Muskingum County
- [ ] Noble County
- [ ] Ottawa County
- [ ] Paulding County
- [ ] Perry County
- [ ] Pickaway County
- [ ] Pike County
- [ ] Portage County
- [ ] Preble County
- [ ] Putnam County
- [ ] Richland County
- [ ] Ross County
- [ ] Sandusky County
- [ ] Scioto County
- [ ] Seneca County
- [ ] Shelby County
- [ ] Stark County
- [ ] Summit County
- [ ] Trumbull County
- [ ] Tuscarawas County
- [ ] Union County
- [ ] Van Wert County
- [ ] Vinton County
- [ ] Warren County
- [ ] Washington County
- [ ] Wayne County
- [ ] Williams County
- [ ] Wood County
- [ ] Wyandot County

**Comment by nvkelso** [comment]
@mxndrwgrdnr Any update from your friend on Ohio precinct GIS map files?

**Comment by nvkelso** [comment]
Added initial 11 counties via https://github.com/nvkelso/election-geodata/issues/115.

![](https://user-images.githubusercontent.com/853051/28993783-e6cd1d12-7973-11e7-837f-526e5e7c402d.png)

**Comment by nvkelso** [comment]
(Note that the maps on the main README aren't updating because CircleCI is being lame.)

**Comment by mxndrwgrdnr** [comment]
@nvkelso just sent him an e-mail I'll let you know when I hear back. He told me that they were "slowly dribbling in" last we talked.

**Comment by mxndrwgrdnr** [comment]
Looks like my connection dried up. He said he's no longer affiliated with the university (OU) and so doesn't have access to the data anymore. I asked to be put in contact with someone there who does. Will follow up here when I hear back.

**Comment by wchatx** [comment]
Just stumbled on this great repo and wanted to chime in with a data acquisition strategy I use for projects like this. Just FYI

Start with google, search using the **inurl** keyword. We're looking for open ArcGIS Server rest endpoints, which are literally everywhere for county governments.

inurl:arcgis/rest/services ohio precinct 2016

The arcgis/rest/services is the URL fragment the site will have if the admin left the defaults in place during configuration, the case probably 99% of the time. Sift through the results looking at the URLs for what are obviously county governments.

Here's a couple of the results just for example's sake:
[https://scgisa.starkcountyohio.gov/arcgis/rest/services/BoardOfElections/General2016Results/MapServer](url)
[http://lcapps.co.lucas.oh.us/arcgis/rest/services/BoardOfElections/Internal/MapServer](url)

Check out the layers, find what you're looking for, then use something like this to scrape the layer down to something usable: [https://github.com/openaddresses/pyesridump](url)

So to get Stark County, OH precincts for 2016, it'd look like this:
`esri2geojson 
 https://scgisa.starkcountyohio.gov/arcgis/rest/services/BoardOfElections/General2016Results/MapServer/0 StarkCountyOHPrecincts.json`

Then convert the GeoJSON to your preferred format using GDAL, QGIS, etc

**Comment by migurski** [comment]
Great suggestion, @wchatx! Esri endpoints are just a fantastic source of otherwise hard-to-find data.

**Comment by nvkelso** [comment]
I received polygons for the following counties... but they're all random little SHP files...

- [ ] Allen
- [ ] Ashtabula
- [ ] Athens
- [ ] Auglaize
- [ ] Belmont
- [ ] Champaign
- [ ] Clark
- [ ] Clinton
- [ ] Coshocton
- [ ] Darke
- [ ] Defiance
- [ ] Delaware
- [ ] Erie
- [ ] Fairfield
- [ ] Fayette
- [ ] Franklin
- [ ] Fulton
- [ ] Gailia
- [ ] Geauga
- [ ] Greene
- [ ] Guernsey
- [ ] Hancock (only Findlay)
- [ ] Henry
- [ ] Hocking
- [ ] Jefferson
- [ ] Knox
- [ ] Lake
- [ ] Logan
- [ ] Lorain
- [ ] Madison
- [ ] Mahoning
- [ ] Marion
- [ ] Medina
- [ ] Mercer
- [ ] Muskingum
- [ ] Ottawa
- [ ] Pickaway
- [ ] Shelby
- [ ] Stark
- [ ] Warren
- [ ] Washington
- [ ] Wayne
- [ ] Williams

**Comment by wboykinm** [comment]
@nvkelso Random like separate or like not representing what they're supposed to?

**Comment by nvkelso** [comment]
With the project polygon shapes (updated the checkboxes in https://github.com/nvkelso/election-geodata/issues/7#issuecomment-296026761) the following large counties are still MIA or broken:

@wboykinm or others can you take a look around for data, please?

- [ ] `39013` **Belmont** shp has problems, find a new copy.
- [ ] `39095` **Lucas** is MIA
- [ ] `39173` **Wood** is MIA
- [ ] `39035` **Cuyahoga** is MIA
- [ ] `39153` **Summit** is MIA
- [ ] `39155` **Trumbull** is MIA

**Comment by skorasaurus** [comment]
Cuyahoga is at https://github.com/nvkelso/election-geodata/issues/127

**Comment by nvkelso** [comment]
Closing in favor of #196.
